config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :marks
  resources :students
  resources :employees
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :e_name,presence: true
    validates :e_name,length: { minimum: 3}
    validates :e_name,length: {maximum: 25}
    validates :sal,numericality:true
    validates :e_name,uniqueness: true
    before_create do self.e_name=e_name.capitalize end
        after_save do message: "#{self.e_name} created" end
    

end

app/models/mark.rb
class Mark < ApplicationRecord
    belongs_to :students
    before_save :merge_total
    before_save :merge_percentage
    def merge_total
        self.total=self.math+self.english+self.science+self.history
    end
    def merge_percentage
        self.percentage=(self.math+self.english+self.science+self.history)/4
        
    end

end

app/models/student.rb
class Student < ApplicationRecord
    has_many :marks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action:authenticate_user!
    def after_sign_in_path_for(resource)
        students_url
    end
    def after_sign_out_path_for(resource)
        students_url
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:e_name, :sal, :place)
    end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: %i[ show edit update destroy ]

  # GET /marks or /marks.json
  def index
    @marks = Mark.all
  end

  # GET /marks/1 or /marks/1.json
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks or /marks.json
  def create
    @mark = Mark.new(mark_params)

    respond_to do |format|
      if @mark.save
        format.html { redirect_to mark_url(@mark), notice: "Mark was successfully created." }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1 or /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to mark_url(@mark), notice: "Mark was successfully updated." }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1 or /marks/1.json
  def destroy
    @mark.destroy

    respond_to do |format|
      format.html { redirect_to marks_url, notice: "Mark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mark_params
      params.require(:mark).permit(:math, :science, :english, :history)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        NotifierMailer.alert_user.deliver
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :std)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :e_name %>
    <%= form.text_field :e_name %>
  </div>

  <div class="field">
    <%= form.label :sal %>
    <%= form.text_field :sal %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>E name</th>
      <th>Sal</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.e_name %></td>
        <td><%= employee.sal %></td>
        <td><%= employee.place %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>E name:</strong>
  <%= @employee.e_name %>
</p>

<p>
  <strong>Sal:</strong>
  <%= @employee.sal %>
</p>

<p>
  <strong>Place:</strong>
  <%= @employee.place %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
  <div class="content">
		<div class="header">
			<div class="top_info">
						

			</div>
			<div class="logo">
				
      <h1><a href="#" title="Centralized Internet Services"><span class="dark">About</span> 
        Myproject</a></h1>
			</div>
		</div>
    <div class="search_field">
			<form method="post" action="?">
				<div class="search_form">
				<p>Search the Web: <input type="text" name="search" class="search" /> <input type="submit" value="Search" class="submit" /></p>
				</div>
			</form>
		</div>
		
		<div class="bar">
			<ul>
				<li class="browse_category">Categories:</li>
				<li><a href="#" accesskey="i">About me</a></li>
				<li class="active">College</li>
				<li><a href="#" accesskey="m">Address</a></li>
				<li><a href="#" accesskey="p">Family</a></li>
				<li><a href="#" accesskey="s">Qualifiaction</a></li>
			</ul>
		</div>
			<% if notice %>
  				<p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
  				<p class="alert alert-danger"><%= alert %></p>
			<% end %>
  
		
    <%= yield %>
	<hr\>
    
		
		
			<p><a href="#">Form</a> | <a href="#">Bootstrap</a><br />
      &copy; Copyright 2022 My Project</p>
		</div>
	</div>
	
   
  </body>
</html>

app/views/marks/_form.html.erb
<%= form_with(model: mark, local: true) do |form| %>
  <% if mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mark.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
        <% mark.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :students_id %>
    <%= form.text_field :students_id %>
  </div>

  <div class="field">
    <%= form.label :math %>
    <%= form.number_field :math %>
  </div>

  <div class="field">
    <%= form.label :science %>
    <%= form.number_field :science %>
  </div>

  <div class="field">
    <%= form.label :english %>
    <%= form.number_field :english %>
  </div>

  <div class="field">
    <%= form.label :history %>
    <%= form.number_field :history %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/marks/edit.html.erb
<h1>Editing Mark</h1>

<%= render 'form', mark: @mark %>

<%= link_to 'Show', @mark %> |
<%= link_to 'Back', marks_path %>

app/views/marks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marks</h1>

<table>
  <thead>
    <tr>
      <th>Math</th>
      <th>Science</th>
      <th>English</th>
      <th>History</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marks.each do |mark| %>
      <tr>
      <td><%= mark.students_id %></td>
        <td><%= mark.math %></td>
        <td><%= mark.science %></td>
        <td><%= mark.english %></td>
        <td><%= mark.history %></td>
        <td><%= link_to 'Show', mark %></td>
        <td><%= link_to 'Edit', edit_mark_path(mark) %></td>
        <td><%= link_to 'Destroy', mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mark', new_mark_path %>

app/views/marks/new.html.erb
<h1>New Mark</h1>

<%= render 'form', mark: @mark %>

<%= link_to 'Back', marks_path %>

app/views/marks/show.html.erb
<p>
  <strong>Math:</strong>
  <%= @mark.math %>
</p>

<p>
  <strong>Science:</strong>
  <%= @mark.science %>
</p>

<p>
  <strong>English:</strong>
  <%= @mark.english %>
</p>

<p>
  <strong>History:</strong>
  <%= @mark.history %>
</p>
<strong>total:</strong>
  <%= (@mark.math+@mark.science+@mark.history+@mark.english) %>

<%= link_to 'Edit', edit_mark_path(@mark) %> |
<%= link_to 'Back', marks_path %>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :std %>
    <%= form.number_field :std %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Std</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.std %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Std:</strong>
  <%= @student.std %>
</p>
<p>
  
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>